name: workbond
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.2
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.1
  introduction_screen: ^3.1.17
  flutter_native_splash: ^2.4.4
  device_preview: ^1.1.0
  icons_plus: ^5.0.0
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/logos/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
